version: '3.3'
services:
  db:
    container_name: 'the_credit_fix-wordpress-db'
    image: 'mysql:5.7'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: the_credit_fix_db
      MYSQL_USER: the_credit_fix_root
      MYSQL_PASSWORD: the_credit_fix_toor

  wordpress:
    container_name: 'the_credit_fix-wordpress'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: the_credit_fix_root
      WORDPRESS_DB_PASSWORD: the_credit_fix_toor
      WORDPRESS_DB_NAME: the_credit_fix_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
